# frontend-nginx-config.yaml (REVERTER NOME DA CHAVE)
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
data:
  default.conf: | # <--- MUDANÇA AQUI: de 'nginx.conf' para 'default.conf'
    server {
        listen 80;

        location ^~ /api/ {
            proxy_pass http://appserver-service:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }