# postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets # Este nome deve corresponder ao 'secretRef.name' no db-deployment.yaml
  namespace: default
type: Opaque
data:
  DB_USER: ZGV2X3VzZXI=      # <--- Mude de POSTGRES_USER para DB_USER
  DB_PASSWORD: ZGV2X3Bhc3M=    # <--- Mude de POSTGRES_PASSWORD para DB_PASSWORD
  DB_NAME: ZGV2X2Ri        # <--- Mude de POSTGRES_DB para DB_NAME