# postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets # Este nome deve corresponder ao 'secretRef.name' no db-deployment.yaml
type: Opaque
data:
  DB_USER: ZGV2X3VzZXI=
  DB_PASSWORD: ZGV2X3Bhc3M=
  DB_NAME: ZGV2X2Ri
  